{{ config(materialized='ephemeral') }}

SELECT [row_id]
      ,[entered_time]
      ,[email_template]
      ,[ref_type]
      ,[ref_id]
      ,[source_type]
      ,[source_id1]
      ,[source_id2]
      ,[source_id3]
      ,[language]
      ,[priority]
      ,[recipients]
      ,[cc_recipients]
      ,[bcc_recipients]
      ,[subject]
      ,[body]
      ,[is_html]
      ,[importance]
      ,[sensitivity]
      ,[request_time]
      ,[preproc_status]
      ,[preproc_time]
      ,[send_status]
      ,[send_time]
      ,[comment_status]
      ,[comment_time]
      ,[udf01_value]
      ,[udf02_value]
      ,[udf03_value]
      ,[udf04_value]
      ,[udf05_value]
      ,[udf06_value]
      ,[udf07_value]
      ,[udf08_value]
      ,[udf09_value]
      ,[udf10_value]
      ,[dataset_id]
      ,[MailItemID]
      ,[ServerName]
      ,[ZLOADDATE] 
 FROM {{ source('dbinterface', 'nls_PCI_email_queue') }}
WHERE 1=1